In [1]:
import numpy as np

# Considering sample data as follows
# X = (hours studying, hours sleeping), y = score on test
xAll = np.array(([2, 9], [1, 5], [3, 6], [5, 10]), dtype=float)  # input data
y = np.array(([92], [86], [89]), dtype=float)  # output

# scale units
xAll = xAll / np.amax(xAll, axis=0)  # scaling input data
y = y / 100  # scaling output data (max test score is 100)

# split data
X = np.split(xAll, [3])[0]  # training data
xPredicted = np.split(xAll, [3])[1]  # testing data

y = np.array(([92], [86], [89]), dtype=float)
y = y / 100  # max test score is 100


class Neural_Network(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3

        #weights
        self.W1 = np.random.randn(
            self.inputSize,
            self.hiddenSize)  # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(
            self.hiddenSize,
            self.outputSize)  # (3x1) weight matrix from hidden to output layer

    def forward(self, X):
        #forward propagation through our network
        self.z = np.dot(
            X,
            self.W1)  # dot product of X (input) and first set of 3x2 weights
        self.z2 = self.sigmoid(self.z)  # activation function
        self.z3 = np.dot(
            self.z2, self.W2
        )  # dot product of hidden layer (z2) and second set of 3x1 weights
        o = self.sigmoid(self.z3)  # final activation function
        return o

    def sigmoid(self, s):
        # activation function
        return 1 / (1 + np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)

    def backward(self, X, y, o):
        # backward propagate through the network
        self.o_error = y - o  # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(
            o)  # applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(
            self.W2.T
        )  # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error * self.sigmoidPrime(
            self.z2)  # applying derivative of sigmoid to z2 error

        self.W1 += X.T.dot(
            self.z2_delta)  # adjusting first set (input --> hidden) weights
        self.W2 += self.z2.T.dot(
            self.o_delta)  # adjusting second set (hidden --> output) weights

    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)

    def saveWeights(self):
        np.savetxt("w1.txt", self.W1, fmt="%s")
        np.savetxt("w2.txt", self.W2, fmt="%s")

    def predict(self):
        print("Predicted data based on trained weights: ")
        print("Input (scaled): \n" + str(xPredicted))
        print("Output: \n" + str(self.forward(xPredicted)))


NN = Neural_Network()
for i in range(1000):  # trains the NN 1,000 times
    print("# " + str(i) + "\n")
    print("Input (scaled): \n" + str(X))
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n" + str(NN.forward(X)))
    print("Loss: \n" +
          str(np.mean(np.square(y - NN.forward(X)))))  # mean sum squared loss
    print("\n")
    NN.train(X, y)

NN.saveWeights()
NN.predict()

# 0

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.34976977]
 [0.38447777]
 [0.33647979]]
Loss: 
0.2858895107002089


# 1

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.46484291]
 [0.48669165]
 [0.44788075]]
Loss: 
0.1806655082208092


# 2

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.56703242]
 [0.57556588]
 [0.54801424]]
Loss: 
0.10748104644354532


# 3

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.6419525 ]
 [0.64062566]
 [0.62227617]]
Loss: 
0.06570385411823611


# 4

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.693628  ]
 [0.68586481]
 [0.67398391]]
Loss: 
0.04274343175039804


# 5

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual

 [0.88787314]]
Loss: 
0.00023042720061601982


# 109

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9013552 ]
 [0.87841113]
 [0.88790286]]
Loss: 
0.00023033211369278888


# 110

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90138182]
 [0.87843379]
 [0.88793143]]
Loss: 
0.0002302399649978979


# 111

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90140742]
 [0.87845539]
 [0.8879589 ]]
Loss: 
0.0002301505232016845


# 112

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90143202]
 [0.87847598]
 [0.88798532]]
Loss: 
0.0002300635755703936


# 113

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90145568]
 [0.87849561]
 [0.88801072]]
Loss: 
0.00022997892645

# 163

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90198171]
 [0.87880798]
 [0.88857967]]
Loss: 
0.00022680543001809127


# 164

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90198566]
 [0.87880755]
 [0.88858404]]
Loss: 
0.00022674848297873942


# 165

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9019895 ]
 [0.87880701]
 [0.88858828]]
Loss: 
0.00022669160127489557


# 166

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90199323]
 [0.87880636]
 [0.88859241]]
Loss: 
0.00022663478239112183


# 167

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90199686]
 [0.87880561]
 [0.88859643]]
Loss: 
0.0002265780240077272


# 168

Input (scaled): 
[[0.4 0.9]
 


# 233

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90212807]
 [0.87864907]
 [0.88874589]]
Loss: 
0.000222922203987161


# 234

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90212936]
 [0.87864605]
 [0.88874741]]
Loss: 
0.00022286795762478225


# 235

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90213065]
 [0.87864303]
 [0.88874893]]
Loss: 
0.00022281374341410792


# 236

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90213194]
 [0.87864   ]
 [0.88875044]]
Loss: 
0.00022275956132512264


# 237

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90213322]
 [0.87863697]
 [0.88875194]]
Loss: 
0.00022270541132845046


# 238

Input (scaled): 
[[0.4 0.9]
 

Loss: 
0.00021765279238573852


# 334

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90224476]
 [0.87833879]
 [0.88888416]]
Loss: 
0.0002176016444417751


# 335

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90224586]
 [0.87833575]
 [0.88888546]]
Loss: 
0.00021755052638534094


# 336

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90224696]
 [0.87833271]
 [0.88888676]]
Loss: 
0.0002174994381953962


# 337

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90224805]
 [0.87832968]
 [0.88888807]]
Loss: 
0.00021744837985092052


# 338

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90224915]
 [0.87832664]
 [0.88888937]]
Loss: 
0.00021739735133089564


# 339

0.0002148834912830209


# 389

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90230451]
 [0.87817359]
 [0.88895504]]
Loss: 
0.00021483395627862044


# 390

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90230558]
 [0.87817063]
 [0.88895631]]
Loss: 
0.00021478445002543668


# 391

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90230666]
 [0.87816766]
 [0.88895759]]
Loss: 
0.00021473497250320165


# 392

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90230773]
 [0.8781647 ]
 [0.88895886]]
Loss: 
0.00021468552369166476


# 393

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90230881]
 [0.87816174]
 [0.88896013]]
Loss: 
0.00021463610357058108


# 394

Inpu

 [0.88904797]]
Loss: 
0.00021124679881361693


# 464

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90238406]
 [0.87795474]
 [0.8890492 ]]
Loss: 
0.00021119936484050603


# 465

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90238511]
 [0.87795187]
 [0.88905044]]
Loss: 
0.00021115195813678763


# 466

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90238615]
 [0.87794901]
 [0.88905168]]
Loss: 
0.00021110457868322172


# 467

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9023872 ]
 [0.87794614]
 [0.88905291]]
Loss: 
0.00021105722646058003


# 468

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90238824]
 [0.87794328]
 [0.88905415]]
Loss: 
0.00021100990


# 511

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90243285]
 [0.8778213 ]
 [0.88910681]]
Loss: 
0.00020900039782345724


# 512

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90243388]
 [0.87781849]
 [0.88910802]]
Loss: 
0.00020895425131076519


# 513

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90243491]
 [0.87781568]
 [0.88910923]]
Loss: 
0.00020890813115904874


# 514

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90243594]
 [0.87781287]
 [0.88911045]]
Loss: 
0.00020886203734970775


# 515

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90243696]
 [0.87781007]
 [0.88911166]]
Loss: 
0.00020881596986414995


# 516

Input (scaled): 
[[0.4 0.9]

Predicted Output: 
[[0.90248995]
 [0.87766592]
 [0.88917405]]
Loss: 
0.00020645627818928665


# 568

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90249095]
 [0.87766318]
 [0.88917523]]
Loss: 
0.00020641157960694673


# 569

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90249196]
 [0.87766044]
 [0.88917642]]
Loss: 
0.00020636690636394278


# 570

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90249297]
 [0.8776577 ]
 [0.88917761]]
Loss: 
0.0002063222584423993


# 571

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90249398]
 [0.87765497]
 [0.88917879]]
Loss: 
0.0002062776358244475


# 572

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90249499]
 [0.

Loss: 
0.00020278825111901919


# 652

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90257452]
 [0.87743736]
 [0.88927327]]
Loss: 
0.00020274561991939167


# 653

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9025755 ]
 [0.87743472]
 [0.88927441]]
Loss: 
0.00020270301260107146


# 654

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90257648]
 [0.87743208]
 [0.88927556]]
Loss: 
0.0002026604291472279


# 655

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90257746]
 [0.87742945]
 [0.88927671]]
Loss: 
0.00020261786954103237


# 656

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90257844]
 [0.87742681]
 [0.88927785]]
Loss: 
0.00020257533376568263


# 65

 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90264714]
 [0.87724272]
 [0.88935802]]
Loss: 
0.00019961517363495957


# 728

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90264809]
 [0.87724017]
 [0.88935913]]
Loss: 
0.0001995743102792695


# 729

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90264905]
 [0.87723762]
 [0.88936024]]
Loss: 
0.00019953346955948816


# 730

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90265   ]
 [0.87723507]
 [0.88936135]]
Loss: 
0.0001994926514596767


# 731

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90265096]
 [0.87723252]
 [0.88936247]]
Loss: 
0.00019945185596391835


# 732

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 

Loss: 
0.00019637724164597243


# 809

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90272445]
 [0.87703716]
 [0.88944775]]
Loss: 
0.00019633816114385618


# 810

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90272538]
 [0.8770347 ]
 [0.88944883]]
Loss: 
0.00019629910202374954


# 811

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90272631]
 [0.87703224]
 [0.8894499 ]]
Loss: 
0.00019626006427062934


# 812

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90272724]
 [0.87702978]
 [0.88945098]]
Loss: 
0.00019622104786948453


# 813

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90272817]
 [0.87702732]
 [0.88945205]]
Loss: 
0.00019618205280531547


# 8

# 890

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90279878]
 [0.87684124]
 [0.88953345]]
Loss: 
0.00019324233875116692


# 891

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90279969]
 [0.87683886]
 [0.88953449]]
Loss: 
0.0001932049626441676


# 892

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90280059]
 [0.87683649]
 [0.88953553]]
Loss: 
0.00019316760672316366


# 893

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9028015 ]
 [0.87683412]
 [0.88953657]]
Loss: 
0.00019313027097400768


# 894

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9028024 ]
 [0.87683174]
 [0.8895376 ]]
Loss: 
0.0001930929553825659


# 895

Input (scaled): 
[[0.4 0.9]
 [

Predicted Output: 
[[0.90286587]
 [0.8766659 ]
 [0.88961025]]
Loss: 
0.00019049420416488078


# 966

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90286675]
 [0.8766636 ]
 [0.88961126]]
Loss: 
0.00019045830344570933


# 967

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90286763]
 [0.8766613 ]
 [0.88961227]]
Loss: 
0.00019042242187995536


# 968

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90286852]
 [0.876659  ]
 [0.88961327]]
Loss: 
0.0001903865594542378


# 969

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9028694 ]
 [0.87665671]
 [0.88961428]]
Loss: 
0.00019035071615517644


# 970

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90287028]
 [0