In [1]:
# importing numpy lib
import numpy as np
import pandas as pd

### Question 1:
Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [2]:
# Declaring two arrays
array1 = np.array([[1,102,8],[69,32,287]])
array2 = np.array([[1,2020,57],[4,89,865]])

# Printing 1st array
print("1st array:")
print(array1)

# Printing 2nd array
print("\n2nd array:")
print(array2)

# checking elements of 1st array are greater than elements of 2nd array
print("\nComparison - greater")
print(np.greater(array1, array2))

# checking elements of 1st array are greater than equal to elements of 2nd array
print("\nComparison - greater_equal")
print(np.greater_equal(array1, array2))

# checking elements of 1st array are less than elements of 2nd array
print("\nComparison - less")
print(np.less(array1, array2))

# checking elements of 1st array are less than equal to elements of 2nd array
print("\nComparison - less_equal")
print(np.less_equal(array1, array2))

1st array:
[[  1 102   8]
 [ 69  32 287]]

2nd array:
[[   1 2020   57]
 [   4   89  865]]

Comparison - greater
[[False False False]
 [ True False False]]

Comparison - greater_equal
[[ True False False]
 [ True False False]]

Comparison - less
[[False  True  True]
 [False  True  True]]

Comparison - less_equal
[[ True  True  True]
 [False  True  True]]


### Question 2:
Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [3]:
# Printing array of 10 zeros
array_of_zeros = np.zeros((5,2))
print('Array of 10 zeros:')
print(array_of_zeros)
print('\nSize of above array:')
print(array_of_zeros.shape)

# Printing array of 10 ones
array_of_ones = np.ones((2,5))
print('\nArray of 10 ones:')
print(array_of_ones)
print('\nSize of above array:')
print(array_of_ones.shape)

# Printing the array of 10 fives
array_of_fives = np.full((10),5) 
print('\nArray of 10 fives:')
print(array_of_fives)
print('\nSize of above array:')
print(array_of_fives.shape)

Array of 10 zeros:
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Size of above array:
(5, 2)

Array of 10 ones:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Size of above array:
(2, 5)

Array of 10 fives:
[5 5 5 5 5 5 5 5 5 5]

Size of above array:
(10,)


### Question 4:
Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [4]:
# Declaring two arrays
array1 = np.array([[1,1022,8],[69,132,287]])
array2 = np.array([[100,2020,57],[46,89,865]])

# Addition of arrays
print('Addition is:')
print(np.add(array1,array2))

# Subtarction of arrays
print('\nSubtraction is:')
print(np.subtract(array1,array2))  

# Multiplication of arrays
print('\nMultiplication is:')
print(np.multiply(array1,array2))

# Division of arrays
print('\nDivision is:')
print(np.divide(array1,array2))

Addition is:
[[ 101 3042   65]
 [ 115  221 1152]]

Subtraction is:
[[ -99 -998  -49]
 [  23   43 -578]]

Multiplication is:
[[    100 2064440     456]
 [   3174   11748  248255]]

Division is:
[[0.01       0.50594059 0.14035088]
 [1.5        1.48314607 0.33179191]]


### Question 5:
Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.

In [5]:
# Declearing the array
array_of_thita = np.array([[90,60,45],[30,180,360]])

# Taking sine of array
print('sin(array):')
print('\n',np.sin(array_of_thita))

# Taking cosine of array
print('\ncos(array):')
print('\n',np.cos(array_of_thita))

# Taking tangent of array
print('\ntan(array):')
print('\n',np.tan(array_of_thita))

sin(array):

 [[ 0.89399666 -0.30481062  0.85090352]
 [-0.98803162 -0.80115264  0.95891572]]

cos(array):

 [[-0.44807362 -0.95241298  0.52532199]
 [ 0.15425145 -0.59846007 -0.28369109]]

tan(array):

 [[-1.99520041  0.32004039  1.61977519]
 [-6.4053312   1.33869021 -3.38014041]]


## Question 6:

In [6]:
# Creating the sample data for the operation
exam_data  = {'name': ['Mayank', 'Abhishek', 'Deva', 'Anay', 'Niraj', 'Akshay', 'Aryan', 'Shekhar', 'Rahul', 'Sameer'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

# Index
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Displaying the Dataframe
df = pd.DataFrame(exam_data , labels)
display(df)

name  score  attempts qualify
a    Mayank   12.5         1     yes
b  Abhishek    9.0         3      no
c      Deva   16.5         2     yes
d      Anay    NaN         3      no
e     Niraj    9.0         2      no
f    Akshay   20.0         3     yes
g     Aryan   14.5         1     yes
h   Shekhar    NaN         1      no
i     Rahul    8.0         2      no
j    Sameer   19.0         1     yes

## Question 7:

In [7]:
# Displaying only the name and score
print("Select specific columns:")
display(df[['name', 'score']])

Select specific columns:


name  score
a    Mayank   12.5
b  Abhishek    9.0
c      Deva   16.5
d      Anay    NaN
e     Niraj    9.0
f    Akshay   20.0
g     Aryan   14.5
h   Shekhar    NaN
i     Rahul    8.0
j    Sameer   19.0

## Question 8:

In [8]:
# Sample data 1
student_data1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Mayank Shelar', 'Deva Masane', 'Atharva Garware', 'Jigar Joshi', 'Rithik Borade'], 
        'marks': [200, 210, 190, 222, 199]})

# Sample data 2
student_data2 = pd.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Vikrant Balmuri', 'Akash Gupta', 'Vikas Gupta', 'Vishal Susar', 'Shubam Haral'], 
        'marks': [201, 200, 198, 219, 201]})

# Displaying Sample data 1
print("Original DataFrames:")
display(student_data1)

print("-------------------------------------")

# Displaying Sample data 2
display(student_data2)

# Main operation of joining
print("\nJoin the said two dataframes along rows:")
result_data = pd.concat([student_data1, student_data2])

# Displaying the result
display(result_data)

Original DataFrames:


student_id             name  marks
0         S1    Mayank Shelar    200
1         S2      Deva Masane    210
2         S3  Atharva Garware    190
3         S4      Jigar Joshi    222
4         S5    Rithik Borade    199

-------------------------------------


student_id             name  marks
0         S4  Vikrant Balmuri    201
1         S5      Akash Gupta    200
2         S6      Vikas Gupta    198
3         S7     Vishal Susar    219
4         S8     Shubam Haral    201


Join the said two dataframes along rows:


student_id             name  marks
0         S1    Mayank Shelar    200
1         S2      Deva Masane    210
2         S3  Atharva Garware    190
3         S4      Jigar Joshi    222
4         S5    Rithik Borade    199
0         S4  Vikrant Balmuri    201
1         S5      Akash Gupta    200
2         S6      Vikas Gupta    198
3         S7     Vishal Susar    219
4         S8     Shubam Haral    201

## Question 9:

In [9]:
# Checking for NaN values
print("Rows where score is missing:")
print(df['score'].isnull())

Rows where score is missing:
a    False
b    False
c    False
d     True
e    False
f    False
g    False
h     True
i    False
j    False
Name: score, dtype: bool


## Question 10:

In [10]:
# Dataframe of array
ds = pd.Series([287, 4, 3.412, 8.314, 6.222])
print(ds)

0    287.000
1      4.000
2      3.412
3      8.314
4      6.222
dtype: float64
